version: "3.1"
services:
  dotnet_tdr_bot:
    container_name: dotnet_tdr_bot_container
    env_file:
      - secrets.env
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    volumes:
      # raspberry pi host path
      - /home/leozhang/files_from_docker/bot_progress/tdr/edge/:/app/configs/edge/screenshots/
# The provided Docker Compose file, with version 3.1, defines a service. This service, represented by the container, is built using the Dockerfile in the current directory. The service runs in host network mode, allowing it to share the host's network namespace. Additionally, the container is set to restart always, ensuring automatic restart in case of any exit.
