version: "3.1"
services:
  amazon_pricetracker:
    container_name: dotnet_amazon_pricetracker
    env_file:
      - secrets.env
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    volumes:
      - /home/leozhang/files_from_docker/amazon_products_outputs/:/app/amazon_products_outputs
# The provided Docker Compose file, with version 3.1, defines a service named docker_test. This service, represented by the container named docker_test, is built using the Dockerfile in the current directory. The service runs in host network mode, allowing it to share the host's network namespace. Additionally, the container is set to restart always, ensuring automatic restart in case of any exit.
