version: "3.1"
services:
  fetch_nasa_pic:
    container_name: fetch_nasa_pic
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    volumes:
      - /home/leozhang/files_from_docker/nasa_pic_collection/:/home/nasa_pic_collection/
# The provided Docker Compose file, with version 3.1, defines a service named fetch_nasa_pic. This service, represented by the container named fetch_nasa_pic, is built using the Dockerfile in the current directory. The service runs in host network mode, allowing it to share the host's network namespace. Additionally, the container is set to restart always, ensuring automatic restart in case of any exit.
