version: "3.1"
services:
  dotnet_news_scraper:
    container_name: dotnet_news_scraper
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: always
# The provided Docker Compose file, with version 3.1, defines a service named dotnet_news_scraper. This service, represented by the container named dotnet_news_scraper, is built using the Dockerfile in the current directory. The service runs in host network mode, allowing it to share the host's network namespace. Additionally, the container is set to restart always, ensuring automatic restart in case of any exit.
